language: node_js
node_js:
  - "11"
addons:
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable
cache:
  directories:
    - node_modules
dist: trusty
sudo: required

install:
  - export CHROME_BIN=/usr/bin/google-chrome
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start

  - export PREV_VERSION=`./vnum.pl 1`
  - export BUILD_VERSION=`./vnum.pl 0`
  - export PREV_PROD_VERSION=`./vnum.pl 3`
  - export BUILD_PROD_VERSION=`./vnum.pl 2`

  - npm install -g @angular/cli
  - npm install -g @angular/fire firebase
  - npm install

script:
- openssl aes256 -md md5 -d -in src/environments/environment.ts.enc -out src/environments/environment.ts -pass pass:$config_pwd
- openssl aes256 -md md5 -d -in src/environments/environment.prod.ts.enc -out src/environments/environment.prod.ts -pass pass:$config_pwd
- ng lint
- ng test --watch=false

after_success:
- git config user.name "Travis"
- git config user.email "hmbarnardt@gmail.com"
- git config push.default simple
- if [ "$TRAVIS_BRANCH" == "staging" ]; then git tag $BUILD_VERSION; git push --tags; fi
- if [ "$TRAVIS_BRANCH" == "master" ]; then git tag $BUILD_PROD_VERSION; git push --tags; fi
- ng build --prod
- firebase deploy